### ISSUE TITLE
Development Tool Install

### ISSUE THREAD

**Issue by Francis0121** [Francis0121/nornenjs.v3#18]
1. Jdk Install
   - sudo apt-get install openjdk-7-jdk
2. Intellij install 
   - https://www.jetbrains.com/idea/download/
3. Android Sdk install
   - https://developer.android.com/sdk/index.html#Other
4. Android Ndk install
   - https://developer.android.com/tools/sdk/ndk/index.html
5. Tizen install 
   - https://developer.tizen.org/ko/downloads/tizen-sdk#2.3

**Comment by Francis0121** [comment]
### Android Sdk, Ndk Build 시

![image](https://cloud.githubusercontent.com/assets/3794501/6896381/be350a6a-d725-11e4-84f6-62c040423473.png)
- local.properties 생성

```
sdk.dir=/home/hyok/android-sdk-linux (SDK directory)
ndk.dir=/home/hyok/android-ndk-r10d (NDK directory)
```

**Comment by uniquerussa** [comment]
intelij 
terminal - alt + f12
디버깅 페이지 - alt + 4
log cat - view-> tool window -> android
start shift + f10
