### ISSUE TITLE
시작발표용 PPT 완성

### ISSUE THREAD

**Issue by Francis0121** [Francis0121/nornenjs.v3#7]
### PPT 남은 부분
- [x] 안드로이드 UI 이벤트 에 대한 PPT (김효연)
- [x] 피드백 부분 (전부)
- [x] 마지막 검토 (전부)

**Comment by Francis0121** [comment]
시작 발표 1차 Template 완성

https://drive.google.com/open?id=0BxcOCyQhJlkQd3VGQkc5NFc5M28&authuser=0

**Comment by Francis0121** [comment]
시작 발표 3차 완성
https://drive.google.com/open?id=0BxcOCyQhJlkQaFk2LVdRYmgwaUk&authuser=0

**Comment by uniquerussa** [comment]
시작 발표 4차 완성

https://drive.google.com/drive/#folders/0BxcOCyQhJlkQZHUydzVhcWg5M00/0BxcOCyQhJlkQOTQ2azk5MG1aa1k

**Comment by Francis0121** [comment]
마지막 PPT
https://drive.google.com/open?id=0BxcOCyQhJlkQeWw2a0UzcVB0TTA&authuser=0

**Comment by hyok** [comment]
시작발표 PPT 효연 파트 내용 추가~
https://drive.google.com/drive/#folders/0BxcOCyQhJlkQZHUydzVhcWg5M00/0BxcOCyQhJlkQOTQ2azk5MG1aa1k

**Comment by Francis0121** [comment]
시작 발표 PPT 발표 테스트 후 수정
https://drive.google.com/open?id=0BxcOCyQhJlkQRkhrRVhsZF9pbWc&authuser=0
