### ISSUE TITLE
시작발표용 문서 완성

### ISSUE THREAD

**Issue by Francis0121** [Francis0121/nornenjs.v3#8]

**Comment by Francis0121** [comment]
시작 문서 수정1차

https://drive.google.com/drive/#folders/0BxcOCyQhJlkQZHUydzVhcWg5M00/0B2k-b4gSvDgwfm9IV2VLMWRBY2U4RTdsdU9RRnhnOEdTR0djRGN0WVRxSlBXYnRWTTVSVmc

#15 Close

**Comment by Francis0121** [comment]
시작 문서 수정 2차 - 서버 웹 부분 1,2,3,4 작성
https://drive.google.com/open?id=0BxcOCyQhJlkQQ0VCSldvX1QxMXM&authuser=0

**Comment by uniquerussa** [comment]
시작 문서 3차  - cuda 부분 작성
안드로이드 부분만 작성하면 완료
https://drive.google.com/drive/#folders/0BxcOCyQhJlkQZHUydzVhcWg5M00/0B2k-b4gSvDgwfm9IV2VLMWRBY2U4RTdsdU9RRnhnOEdTR0djRGN0WVRxSlBXYnRWTTVSVmc

**Comment by hyok** [comment]
시작 문서 3차 - 안드로이드 부분 작성완료
TF 부분 내용 웅규오빠가 확인 바람
https://drive.google.com/drive/#folders/0BxcOCyQhJlkQZHUydzVhcWg5M00/0B2k-b4gSvDgwfm9IV2VLMWRBY2U4RTdsdU9RRnhnOEdTR0djRGN0WVRxSlBXYnRWTTVSVmc

**Comment by Francis0121** [comment]
문서 완료
https://drive.google.com/open?id=0B2k-b4gSvDgwcFBCNkNaZEk2SkU&authuser=0
